name: BuildReset
main: darealaqua\buildreset\Main
author: DaRealAqua
version: 0.0.1
api: 4.0.0

permissions:
  buildreset.permission:
    default: op
    description: Edit build reset settings.