name: BuildReset
main: darealaqua\buildreset\Main
author: DaRealAqua
version: 0.0.2
api: 5.0.0

permissions:
  buildreset.permission:
    default: op
    description: Edit build reset settings.