# Enable build reset in worlds...
# You can add worlds manually or with the /buildreset command.
worlds:
  - world

# Edit blocks despawn countdown.
# You can manage when the blocks should disappear.
despawn_countdown: 5

# Edit blocks despawn particle.
# You can manage whether to show the block particles or not.
despawn_particle: true