# Build Reset Configuration
# Author: @DaRealAqua
# Twitter: @DaRealAqua_

# Worlds where build reset is enabled
enabled_worlds:
  - world

# Sets the countdown for when blocks should disappear after being broken. Default is 5 seconds.
despawn_countdown: 5

# Determines whether to show particles when blocks despawn after being broken. Default is true.
despawn_particle: true
